-- =============================================
-- Author:		<Rashmi Gupta>
-- Create date: <08-01-2024>
-- Description:	<Get the Reports Type from SD_Reports_Type_Master>
-- =============================================
